/*
  See info about updating this in `./index.d.ts`
*/

exports.thjodskraPlaces = {
  // Sveitarfélög
  // ---------------------------------------------------------------------------
  '0000': 'Reykjavíkurborg',
  '1000': 'Kópavogsbær',
  '1100': 'Seltjarnarnesbær',
  '1300': 'Garðabær',
  '1400': 'Hafnarfjarðarkaupstaður',
  '1604': 'Mosfellsbær',
  '1606': 'Kjósarhreppur',
  '2000': 'Reykjanesbær',
  '2300': 'Grindavíkurbær',
  '2506': 'Sveitarfélagið Vogar',
  '2510': 'Suðurnesjabær',
  '3000': 'Akraneskaupstaður',
  '3506': 'Skorradalshreppur',
  '3511': 'Hvalfjarðarsveit',
  '3609': 'Borgarbyggð',
  '3709': 'Grundarfjarðarbær',
  '3713': 'Eyja- og Miklaholtshreppur',
  '3714': 'Snæfellsbær',
  '3716': 'Stykkishólmsbær og Helgafellssveit',
  '3811': 'Dalabyggð',
  '4100': 'Bolungarvíkurkaupstaður',
  '4200': 'Ísafjarðarbær',
  '4502': 'Reykhólahreppur',
  '4604': 'Tálknafjarðarhreppur',
  '4607': 'Vesturbyggð',
  '4803': 'Súðavíkurhreppur',
  '4901': 'Árneshreppur',
  '4902': 'Kaldrananeshreppur',
  '4911': 'Strandabyggð',
  '5508': 'Húnaþing vestra',
  '5609': 'Sveitarfélagið Skagaströnd',
  '5611': 'Skagabyggð',
  '5613': 'Blönduósbær og Húnavatnshreppur',
  '5716': 'Sveitarfélagið Skagafjörður og Akrahreppur',
  '6000': 'Akureyrarkaupstaður',
  '6100': 'Norðurþing',
  '6250': 'Fjallabyggð',
  '6400': 'Dalvíkurbyggð',
  '6513': 'Eyjafjarðarsveit',
  '6515': 'Hörgársveit',
  '6601': 'Svalbarðsstrandarhreppur',
  '6602': 'Grýtubakkahreppur',
  '6611': 'Tjörneshreppur',
  '6613': 'Skútustaðahreppur og Þingeyjarsveit',
  '6710': 'Langanesbyggð og Svalbarðshreppur',
  '7300': 'Fjarðabyggð',
  '7400': 'Múlaþing    ',
  '7502': 'Vopnafjarðarhreppur',
  '7505': 'Fljótsdalshreppur',
  '8000': 'Vestmannaeyjabær',
  '8200': 'Sveitarfélagið Árborg',
  '8401': '	Sveitarfélagið Hornafjörður ',
  '8508': 'Mýrdalshreppur',
  '8509': 'Skaftárhreppur',
  '8610': 'Ásahreppur',
  '8613': 'Rangárþing eystra',
  '8614': 'Rangárþing ytra',
  '8710': 'Hrunamannahreppur',
  '8716': 'Hveragerðisbær',
  '8717': 'Sveitarfélagið Ölfus',
  '8719': 'Grímsnes- og Grafningshreppur',
  '8720': 'Skeiða- og Gnúpverjahreppur',
  '8721': 'Bláskógabyggð',
  '8722': 'Flóahreppur',

  // Staðir
  // ---------------------------------------------------------------------------
  '1603': 'Sveitarfélagið Álftanes',
  '1605': 'Kjalarneshreppur',
  '2200': 'Keflavík',
  '2400': 'Njarðvík',
  '2500': 'Gullbringusýsla',
  '2502': 'Hafnarhreppur',
  '2507': 'Garðahreppur',
  '2508': 'Bessastaðahreppur',
  '2509': 'Keflavíkurflugvöllur',
  '2600': 'Kjósarsýsla',
  '2603': 'Kjalarneshreppur',
  '2604': 'Kjósarhreppur',
  '2700': 'Gullbringu- og Kjósarsýslur',
  '3200': 'Ólafsvík',
  '3500': 'Borgarfjarðarsýsla',
  '3501': 'Hvalfjarðarstrandarhreppur',
  '3502': 'Skilmannahreppur',
  '3503': 'Innri-Akraneshreppur',
  '3504': 'Leirár- og Melahreppur',
  '3505': 'Andakílshreppur',
  '3507': 'Lundarreykjadalshreppur',
  '3508': 'Reykholtsdalshreppur',
  '3509': 'Hálsahreppur',
  '3510': 'Borgarfjarðarsveit',
  '3600': 'Mýrasýsla',
  '3601': 'Hvítársíðuhreppur',
  '3602': 'Þverárhlíðarhreppur',
  '3603': 'Norðurárdalshreppur',
  '3604': 'Stafholtstungnahreppur',
  '3605': 'Borgarhreppur',
  '3606': 'Borgarnes',
  '3607': 'Álftaneshreppur',
  '3608': 'Hraunhreppur',
  '3700': 'Snæfellsnessýsla',
  '3701': 'Kolbeinsstaðahreppur',
  '3702': 'Eyjahreppur',
  '3703': 'Miklaholtshreppur',
  '3704': 'Staðarsveit',
  '3705': 'Breiðuvíkurhreppur',
  '3706': 'Neshreppur',
  '3707': 'Ólafsvíkurhreppur',
  '3708': 'Fróðárhreppur',
  '3712': 'Skógarstrandarhreppur',
  '3715': 'Stykkishólmsbær',
  '3800': 'Dalasýsla',
  '3801': 'Hörðudalshreppur',
  '3802': 'Miðdalahreppur',
  '3803': 'Haukadalshreppur',
  '3804': 'Laxárdalshreppur',
  '3805': 'Hvammshreppur',
  '3806': 'Fellsstrandarhreppur',
  '3807': 'Klofningshreppur',
  '3808': 'Skarðshreppur',
  '3809': 'Saurbæjarhreppur',
  '3810': 'Suðurdalahreppur',
  '4000': 'Ísafjörður',
  '4300': 'Barðastrandarsýslur',
  '4400': 'Ísafjarðarsýslur',
  '4500': 'Austur-Barðastrandarsýsla',
  '4501': 'Geiradalshreppur',
  '4503': 'Gufudalshreppur',
  '4504': 'Múlahreppur',
  '4505': 'Flateyjarhreppur',
  '4600': 'Vestur-Barðastrandarsýsla',
  '4601': 'Barðastrandarhreppur',
  '4602': 'Rauðasandshreppur',
  '4603': 'Patrekshreppur',
  '4605': 'Ketildalahreppur',
  // '4606':'Suðurfjarðahreppur',
  '4606': 'Bíldudalshreppur',
  '4700': 'Vestur-Ísafjarðarsýsla',
  '4701': 'Auðkúluhreppur',
  '4702': 'Þingeyrarhreppur',
  '4703': 'Mýrahreppur',
  '4704': 'Mosvallahreppur',
  '4705': 'Flateyrarhreppur',
  '4706': 'Suðureyrarhreppur',
  '4800': 'Norður-Ísafjarðarsýsla',
  '4802': 'Eyrarhreppur',
  '4804': 'Ögurhreppur',
  '4805': 'Reykjarfjarðarhreppur',
  '4806': 'Nauteyrarhreppur',
  '4807': 'Snæfjallahreppur',
  '4808': 'Grunnavíkurhreppur',
  '4809': 'Sléttuhreppur',
  '4900': 'Strandasýsla',
  '4903': 'Hrófbergshreppur',
  '4904': 'Hólmavíkurhreppur',
  '4905': 'Kirkjubólshreppur',
  '4906': 'Fellshreppur',
  '4907': 'Óspakseyrarhreppur',
  '4908': 'Bæjarhreppur',
  '4909': 'Broddaneshreppur',
  '4910': 'Hólmavíkurhreppur',
  '5000': 'Siglufjörður',
  '5100': 'Sauðárkrókur',
  '5500': 'Vestur-Húnavatnssýsla',
  '5501': 'Staðarhreppur',
  '5502': 'Fremri-Torfustaðahreppur',
  '5503': 'Ytri-Torfustaðahreppur',
  '5504': 'Hvammstangahreppur',
  '5505': 'Kirkjuhvammshreppur',
  '5506': 'Þverárhreppur',
  '5507': 'Þorkelshólshreppur',
  '5600': 'Austur-Húnavatnssýsla',
  '5601': 'Áshreppur',
  '5602': 'Sveinsstaðahreppur',
  '5603': 'Torfalækjarhreppur',
  '5605': 'Svínavatnshreppur',
  '5606': 'Bólstaðarhlíðarhreppur',
  '5607': 'Engihlíðarhreppur',
  '5608': 'Vindhælishreppur',
  '5610': 'Skagahreppur',
  '5700': 'Skagafjarðarsýsla',
  '5701': 'Skefilsstaðahreppur',
  '5702': 'Skarðshreppur',
  '5703': 'Staðarhreppur',
  '5704': 'Seyluhreppur',
  '5705': 'Lýtingsstaðahreppur',
  '5707': 'Rípurhreppur',
  '5708': 'Viðvíkurhreppur',
  '5709': 'Hólahreppur',
  '5710': 'Hofshreppur',
  '5711': 'Hofsóshreppur',
  '5712': 'Fellshreppur',
  '5713': 'Haganeshreppur',
  '5714': 'Holtshreppur',
  '5715': 'Fljótahreppur',
  '5800': 'Húnavatnssýslur',
  '6200': 'Ólafsfjörður',
  '6300': 'Dalvík',
  '6500': 'Eyjafjarðarsýsla',
  '6501': 'Grímseyjarhreppur',
  '6502': 'Svarfaðardalshreppur',
  '6504': 'Hríseyjarhreppur',
  '6505': 'Árskógshreppur',
  '6506': 'Arnarneshreppur',
  '6507': 'Skriðuhreppur',
  '6508': 'Öxnadalshreppur',
  '6509': 'Glæsibæjarhreppur',
  '6510': 'Hrafnagilshreppur',
  '6511': 'Saurbæjarhreppur',
  '6512': 'Öngulsstaðahreppur',
  '6514': 'Hörgárbyggð',
  '6600': 'Suður-Þingeyjarsýsla',
  '6603': 'Flateyjarhreppur',
  '6604': 'Hálshreppur',
  '6605': 'Ljósavatnshreppur',
  '6606': 'Bárðdælahreppur',
  '6608': 'Reykdælahreppur',
  '6609': 'Aðaldælahreppur',
  '6610': 'Reykjahreppur',
  '6700': 'Norður-Þingeyjarsýsla',
  '6701': 'Kelduneshreppur',
  '6702': 'Öxarfjarðarhreppur',
  '6703': 'Fjallahreppur',
  '6704': 'Presthólahreppur',
  '6705': 'Raufarhafnarhreppur',
  '6707': 'Þórshafnarhreppur',
  '6708': 'Sauðaneshreppur',
  '6800': 'Þingeyjarsýslur',
  '7100': 'Neskaupstaður',
  '7200': 'Eskifjörður',
  '7500': 'Norður-Múlasýsla',
  '7501': 'Skeggjastaðahreppur',
  '7503': 'Hlíðarhreppur',
  '7504': 'Jökuldalshreppur',
  '7506': 'Fellahreppur',
  '7507': 'Tunguhreppur',
  '7508': 'Hjaltastaðarhreppur',
  '7510': 'Loðmundarfjarðarhreppur',
  '7511': 'Seyðisfjarðarhreppur',
  '7512': 'Norður-Hérað',
  '7600': 'Suður-Múlasýsla',
  '7601': 'Skriðdalshreppur',
  '7602': 'Vallahreppur',
  '7603': 'Egilsstaðir',
  '7604': 'Eiðahreppur',
  '7605': 'Mjóafjarðarhreppur',
  '7606': 'Norðfjarðarhreppur',
  '7607': 'Helgustaðahreppur',
  '7609': 'Reyðarfjarðarhreppur',
  '7610': 'Fáskrúðsfjarðarhreppur',
  '7611': 'Búðahreppur',
  '7612': 'Stöðvarhreppur',
  '7614': 'Beruneshreppur',
  '7615': 'Búlandshreppur',
  '7616': 'Geithellnahreppur',
  '7618': 'Austur-Hérað',
  '7619': 'Austurbyggð',
  '7700': 'Austur-Skaftafellssýsla',
  '7701': 'Bæjarhreppur',
  '7702': 'Nesjahreppur',
  '7703': 'Höfn í Hornafirði',
  '7704': 'Mýrahreppur',
  '7705': 'Borgarhafnarhreppur',
  '7706': 'Hofshreppur',
  '7707': 'Hornafjarðarbær',
  '8100': 'Selfoss',
  '8500': 'Vestur-Skaftafellssýsla',
  '8501': 'Hörgslandshreppur',
  '8502': 'Kirkjubæjarhreppur',
  '8503': 'Skaftártunguhreppur',
  '8504': 'Leiðvallarhreppur',
  '8505': 'Álftavershreppur',
  '8506': 'Hvammshreppur',
  '8507': 'Dyrhólahreppur',
  '8600': 'Rangárvallasýsla',
  '8601': 'Austur-Eyjafjallahreppur',
  '8602': 'Vestur-Eyjafjallahreppur',
  '8603': 'Austur-Landeyjahreppur',
  '8604': 'Vestur-Landeyjahreppur',
  '8605': 'Fljótshlíðarhreppur',
  '8606': 'Hvolhreppur',
  '8607': 'Rangárvallahreppur',
  '8608': 'Landmannahreppur',
  '8609': 'Holtahreppur',
  '8611': 'Djúpárhreppur',
  '8612': 'Holta- og Landsveit',
  '8700': 'Árnessýsla',
  '8701': 'Gaulverjabæjarhreppur',
  '8702': 'Stokkseyrarhreppur',
  '8703': 'Eyrarbakkahreppur',
  '8704': 'Sandvíkurhreppur',
  '8705': 'Selfosshreppur',
  '8706': 'Hraungerðishreppur',
  '8707': 'Villingaholtshreppur',
  '8708': 'Skeiðahreppur',
  '8709': 'Gnúpverjahreppur',
  '8711': 'Biskupstungnahreppur',
  '8712': 'Laugardalshreppur',
  '8713': 'Grímsneshreppur',
  '8714': 'Þingvallahreppur',
  '8715': 'Grafningshreppur',
  '8718': 'Selvogshreppur',

  // Lönd
  // ---------------------------------------------------------------------------
  AD: 'Andorra',
  AE: 'Sameinuð arabafurstadæmi',
  AF: 'Afganistan',
  AG: 'Antígva og Barbúda',
  AL: 'Albanía',
  AM: 'Armenía',
  AN: 'Hollensku Antillur',
  AO: 'Angóla',
  AR: 'Argentína',
  AT: 'Austurríki',
  AU: 'Ástralía',
  AW: 'Arúba',
  AZ: 'Aserbaídsjan',
  BA: 'Bosnía og Hersegóvína',
  BB: 'Barbados',
  BD: 'Bangladess',
  BE: 'Belgía',
  BF: 'Búrkína-Fasó',
  BG: 'Búlgaría',
  BH: 'Barein',
  BI: 'Búrúndí',
  BJ: 'Benín',
  BM: 'Bermúda',
  BN: 'Brúnei',
  BO: 'Bólivía',
  BR: 'Brasilía',
  BS: 'Bahamaeyjar',
  BY: 'Hvíta-Rússland',
  BZ: 'Belís',
  CA: 'Kanada',
  CD: 'Austur-Kongó',
  CF: 'Miðafríka',
  CG: 'Kongó',
  CH: 'Sviss',
  CI: 'Fílabeinsströnd',
  CL: 'Chile',
  CM: 'Kamerún',
  CN: 'Kína',
  CO: 'Kólumbía',
  CR: 'Costa-Ríca',
  CS: 'Serbía og Svartfjallaland',
  CU: 'Kúba',
  CV: 'Grænhöfðaeyjar',
  CW: 'Curacao',
  CY: 'Kýpur',
  CZ: 'Tékkland',
  DD: 'Austur-Þýskaland',
  DE: 'Þýskaland',
  DJ: 'Díbútí',
  DK: 'Danmörk',
  DM: 'Dóminíka',
  DO: 'Dóminíska lýðveldið',
  DZ: 'Alsír',
  EC: 'Ekvador',
  EE: 'Eistland',
  EG: 'Egyptaland',
  ER: 'Erítrea',
  ES: 'Spánn',
  ET: 'Eþíópía',
  FI: 'Finnland',
  FJ: 'Fídji',
  FO: 'Færeyjar',
  FR: 'Frakkland',
  GA: 'Gabon',
  GB: 'Bretland',
  GD: 'Grenada',
  GE: 'Georgía',
  GH: 'Ghana',
  GI: 'Gíbraltar',
  GL: 'Grænland',
  GM: 'Gambía',
  GN: 'Gínea',
  GQ: 'Miðbaugsgínea',
  GR: 'Grikkland',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Gínea-Bissá',
  GY: 'Guyana',
  HK: 'Hongkong',
  HN: 'Hondúras',
  HR: 'Króatía',
  HT: 'Haítí',
  HU: 'Ungverjaland',
  ID: 'Indónesía',
  IE: 'Írland',
  IL: 'Ísrael',
  IN: 'Indland',
  IQ: 'Írak',
  IR: 'Íran',
  IT: 'Ítalía',
  JE: 'Jersey',
  JM: 'Jamaíka',
  JO: 'Jórdanía',
  JP: 'Japan',
  KE: 'Kenía',
  KG: 'Kirgistan',
  KH: 'Kambódía',
  KM: 'Kómóróeyjar',
  KN: 'St. Kitts og Nevis',
  KP: 'Norður-Kórea',
  KR: 'Suður-Kórea',
  KW: 'Kúvaít',
  KY: 'Caymaneyjar',
  KZ: 'Kasakstan',
  LA: 'Laos',
  LB: 'Líbanon',
  LC: 'Sankti-Lúsía',
  LI: 'Liechtenstein',
  LK: 'Srí Lanka',
  LR: 'Líbería',
  LS: 'Lesótó',
  LT: 'Litáen',
  LU: 'Lúxemborg',
  LV: 'Lettland',
  LY: 'Líbía',
  MA: 'Marokkó',
  MC: 'Mónakó',
  MD: 'Moldova',
  ME: 'Svartfjallaland',
  MG: 'Madagaskar',
  MK: 'Makedónía',
  ML: 'Malí',
  MM: 'Mýanmar',
  MN: 'Mongólía',
  MQ: 'Martiník',
  MR: 'Máritanía',
  MT: 'Malta',
  MU: 'Máritíus',
  MV: 'Maldíveyjar',
  MW: 'Malaví',
  MX: 'Mexíkó',
  MY: 'Malasía',
  MZ: 'Mósambik',
  NA: 'Namibía',
  NE: 'Níger',
  NG: 'Nígería',
  NI: 'Níkaragva',
  NL: 'Holland',
  NO: 'Noregur',
  NP: 'Nepal',
  NR: 'Naúrú',
  NZ: 'Nýja-Sjáland',
  OM: 'Óman',
  PA: 'Panama',
  PE: 'Perú',
  PG: 'Papúa Nýja-Gínea',
  PH: 'Filippseyjar',
  PK: 'Pakistan',
  PL: 'Pólland',
  PR: 'Púertó-Ríco',
  PS: 'Palestína',
  PT: 'Portúgal',
  PY: 'Paraguay',
  QA: 'Katar',
  XK: 'Kósóvó',
  QZ: 'Tékkóslóvakía',
  RE: 'Réunion',
  RO: 'Rúmenía',
  RS: 'Serbía',
  RU: 'Rússland',
  RW: 'Rúanda',
  SA: 'Saúdí-Arabía',
  SB: 'Salómonseyjar',
  SD: 'Súdan',
  SE: 'Svíþjóð',
  SG: 'Singapúr',
  SI: 'Slóvenía',
  SJ: 'Svalbarði og Jan Mayen',
  SK: 'Slóvakía',
  SL: 'Síerra Leóne',
  SM: 'San Marínó',
  SN: 'Senegal',
  SO: 'Sómalía',
  SR: 'Súrínam',
  SS: 'Suður-Súdan',
  ST: 'Saó Tóme og Prinsípe',
  SU: 'Sovétríkin',
  SV: 'El Salvador',
  SY: 'Sýrland',
  TG: 'Tógó',
  TH: 'Taíland',
  TJ: 'Tadjikistan',
  TL: 'Austur-Tímor',
  TM: 'Túrkmenistan',
  TN: 'Túnis',
  TO: 'Tonga',
  TR: 'Tyrkland',
  TT: 'Trínidad og Tobagó',
  TW: 'Taívan',
  TZ: 'Tansanía',
  UA: 'Úkraína',
  UG: 'Úganda',
  US: 'Bandaríkin',
  UY: 'Úruguay',
  UZ: 'Úsbekistan',
  VC: 'St.Vincent og Grenadines',
  VE: 'Venesúela',
  VN: 'Víetnam',
  XR: 'Evrópa, ótilgreint land',
  XS: 'Ameríka, ótilgreint land',
  XT: 'Afríka, ótilgreint land',
  XU: 'Asía, ótilgreint land',
  XV: 'Eyjaálfa, ótilgreint land',
  XX: 'Útlönd, ótilgreint land',
  XZ: 'Ríkisfangslaus einstaklingur',
  YE: 'Jemen',
  YU: 'Júgóslavía',
  ZA: 'Suður-Afríka',
  ZM: 'Sambía',
  ZW: 'Simbabve',
};
